version: '3.1'
services:
  postgresqldb:
    container_name: postgresdb
    image: postgres:9.6
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_DB=students
 
  springapi:
    container_name: springboot
    image: springboot
    ports:
    - 8080:8080
    environment:
      - SPRING.DATASOURCE.URL=jdbc:postgresql://postgresqldb:5432/students
    depends_on:
    - postgresqldb
    
  angular:
    image: nginx:alpine
    container_name: angular
    ports: 
    - 4200:4200
    depends_on:
    - springapi
    volumes:
    - C:\Users\juand\my-test-app/nginx.conf:/etc/nginx/nginx.conf
    - C:\Users\juand\my-test-app\dist\my-test-app\:/usr/share/nginx/html

      

   