version: '3.1'
services:
  postgresqldb:
    container_name: postgresdb
    image: postgres:9.6
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_DB=students
  app:
    container_name: springboot
    image: springboot
    ports:
    - 8080:8080
    environment:
      - SPRING.DATASOURCE.URL=jdbc:postgresql://postgresqldb:5432/students
    depends_on:
    - postgresqldb